/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ControlRouteImport } from './routes/control'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPlayersRouteImport } from './routes/admin/players'
import { Route as AdminResultsRouteImport } from './routes/admin/results'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTournamentsRouteImport } from './routes/admin/tournaments'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppReferRouteImport } from './routes/app/refer'
import { Route as AppWalletRouteImport } from './routes/app/wallet'
import { Route as ControlIndexRouteImport } from './routes/control/index'
import { Route as ControlAnnouncementsRouteImport } from './routes/control/announcements'
import { Route as ControlAuditRouteImport } from './routes/control/audit'
import { Route as ControlBannersRouteImport } from './routes/control/banners'
import { Route as ControlContentRouteImport } from './routes/control/content'
import { Route as ControlPaymentsRouteImport } from './routes/control/payments'
import { Route as ControlPlayersRouteImport } from './routes/control/players'
import { Route as ControlResultsRouteImport } from './routes/control/results'
import { Route as ControlRulesRouteImport } from './routes/control/rules'
import { Route as ControlSettingsRouteImport } from './routes/control/settings'
import { Route as ControlTournamentsRouteImport } from './routes/control/tournaments'
import { Route as AppTournamentIdRouteImport } from './routes/app/tournament.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReferRoute = AppReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const ControlIndexRoute = ControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRoute,
} as any)
const ControlAnnouncementsRoute = ControlAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ControlRoute,
} as any)
const ControlAuditRoute = ControlAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ControlRoute,
} as any)
const ControlBannersRoute = ControlBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => ControlRoute,
} as any)
const ControlContentRoute = ControlContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => ControlRoute,
} as any)
const ControlPaymentsRoute = ControlPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ControlRoute,
} as any)
const ControlPlayersRoute = ControlPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => ControlRoute,
} as any)
const ControlResultsRoute = ControlResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ControlRoute,
} as any)
const ControlRulesRoute = ControlRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => ControlRoute,
} as any)
const ControlSettingsRoute = ControlSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ControlRoute,
} as any)
const ControlTournamentsRoute = ControlTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => ControlRoute,
} as any)
const AppTournamentIdRoute = AppTournamentIdRouteImport.update({
  id: '/tournament/$id',
  path: '/tournament/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/control': typeof ControlRouteWithChildren
  '/download': typeof DownloadRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refer': typeof AppReferRoute
  '/app/wallet': typeof AppWalletRoute
  '/control/announcements': typeof ControlAnnouncementsRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/banners': typeof ControlBannersRoute
  '/control/content': typeof ControlContentRoute
  '/control/payments': typeof ControlPaymentsRoute
  '/control/players': typeof ControlPlayersRoute
  '/control/results': typeof ControlResultsRoute
  '/control/rules': typeof ControlRulesRoute
  '/control/settings': typeof ControlSettingsRoute
  '/control/tournaments': typeof ControlTournamentsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/control/': typeof ControlIndexRoute
  '/app/tournament/$id': typeof AppTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refer': typeof AppReferRoute
  '/app/wallet': typeof AppWalletRoute
  '/control/announcements': typeof ControlAnnouncementsRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/banners': typeof ControlBannersRoute
  '/control/content': typeof ControlContentRoute
  '/control/payments': typeof ControlPaymentsRoute
  '/control/players': typeof ControlPlayersRoute
  '/control/results': typeof ControlResultsRoute
  '/control/rules': typeof ControlRulesRoute
  '/control/settings': typeof ControlSettingsRoute
  '/control/tournaments': typeof ControlTournamentsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/control': typeof ControlIndexRoute
  '/app/tournament/$id': typeof AppTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/control': typeof ControlRouteWithChildren
  '/download': typeof DownloadRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refer': typeof AppReferRoute
  '/app/wallet': typeof AppWalletRoute
  '/control/announcements': typeof ControlAnnouncementsRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/banners': typeof ControlBannersRoute
  '/control/content': typeof ControlContentRoute
  '/control/payments': typeof ControlPaymentsRoute
  '/control/players': typeof ControlPlayersRoute
  '/control/results': typeof ControlResultsRoute
  '/control/rules': typeof ControlRulesRoute
  '/control/settings': typeof ControlSettingsRoute
  '/control/tournaments': typeof ControlTournamentsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/control/': typeof ControlIndexRoute
  '/app/tournament/$id': typeof AppTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/control'
    | '/download'
    | '/admin/announcements'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/refer'
    | '/app/wallet'
    | '/control/announcements'
    | '/control/audit'
    | '/control/banners'
    | '/control/content'
    | '/control/payments'
    | '/control/players'
    | '/control/results'
    | '/control/rules'
    | '/control/settings'
    | '/control/tournaments'
    | '/admin/'
    | '/app/'
    | '/control/'
    | '/app/tournament/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/admin/announcements'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/refer'
    | '/app/wallet'
    | '/control/announcements'
    | '/control/audit'
    | '/control/banners'
    | '/control/content'
    | '/control/payments'
    | '/control/players'
    | '/control/results'
    | '/control/rules'
    | '/control/settings'
    | '/control/tournaments'
    | '/admin'
    | '/app'
    | '/control'
    | '/app/tournament/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/control'
    | '/download'
    | '/admin/announcements'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/refer'
    | '/app/wallet'
    | '/control/announcements'
    | '/control/audit'
    | '/control/banners'
    | '/control/content'
    | '/control/payments'
    | '/control/players'
    | '/control/results'
    | '/control/rules'
    | '/control/settings'
    | '/control/tournaments'
    | '/admin/'
    | '/app/'
    | '/control/'
    | '/app/tournament/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ControlRoute: typeof ControlRouteWithChildren
  DownloadRoute: typeof DownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/refer': {
      id: '/app/refer'
      path: '/refer'
      fullPath: '/app/refer'
      preLoaderRoute: typeof AppReferRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/control/': {
      id: '/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof ControlIndexRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/announcements': {
      id: '/control/announcements'
      path: '/announcements'
      fullPath: '/control/announcements'
      preLoaderRoute: typeof ControlAnnouncementsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/audit': {
      id: '/control/audit'
      path: '/audit'
      fullPath: '/control/audit'
      preLoaderRoute: typeof ControlAuditRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/banners': {
      id: '/control/banners'
      path: '/banners'
      fullPath: '/control/banners'
      preLoaderRoute: typeof ControlBannersRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/content': {
      id: '/control/content'
      path: '/content'
      fullPath: '/control/content'
      preLoaderRoute: typeof ControlContentRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/payments': {
      id: '/control/payments'
      path: '/payments'
      fullPath: '/control/payments'
      preLoaderRoute: typeof ControlPaymentsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/players': {
      id: '/control/players'
      path: '/players'
      fullPath: '/control/players'
      preLoaderRoute: typeof ControlPlayersRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/results': {
      id: '/control/results'
      path: '/results'
      fullPath: '/control/results'
      preLoaderRoute: typeof ControlResultsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/rules': {
      id: '/control/rules'
      path: '/rules'
      fullPath: '/control/rules'
      preLoaderRoute: typeof ControlRulesRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/settings': {
      id: '/control/settings'
      path: '/settings'
      fullPath: '/control/settings'
      preLoaderRoute: typeof ControlSettingsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/tournaments': {
      id: '/control/tournaments'
      path: '/tournaments'
      fullPath: '/control/tournaments'
      preLoaderRoute: typeof ControlTournamentsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/app/tournament/$id': {
      id: '/app/tournament/$id'
      path: '/tournament/$id'
      fullPath: '/app/tournament/$id'
      preLoaderRoute: typeof AppTournamentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferRoute: typeof AppReferRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTournamentIdRoute: typeof AppTournamentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferRoute: AppReferRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppTournamentIdRoute: AppTournamentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ControlRouteChildren {
  ControlAnnouncementsRoute: typeof ControlAnnouncementsRoute
  ControlAuditRoute: typeof ControlAuditRoute
  ControlBannersRoute: typeof ControlBannersRoute
  ControlContentRoute: typeof ControlContentRoute
  ControlPaymentsRoute: typeof ControlPaymentsRoute
  ControlPlayersRoute: typeof ControlPlayersRoute
  ControlResultsRoute: typeof ControlResultsRoute
  ControlRulesRoute: typeof ControlRulesRoute
  ControlSettingsRoute: typeof ControlSettingsRoute
  ControlTournamentsRoute: typeof ControlTournamentsRoute
  ControlIndexRoute: typeof ControlIndexRoute
}

const ControlRouteChildren: ControlRouteChildren = {
  ControlAnnouncementsRoute: ControlAnnouncementsRoute,
  ControlAuditRoute: ControlAuditRoute,
  ControlBannersRoute: ControlBannersRoute,
  ControlContentRoute: ControlContentRoute,
  ControlPaymentsRoute: ControlPaymentsRoute,
  ControlPlayersRoute: ControlPlayersRoute,
  ControlResultsRoute: ControlResultsRoute,
  ControlRulesRoute: ControlRulesRoute,
  ControlSettingsRoute: ControlSettingsRoute,
  ControlTournamentsRoute: ControlTournamentsRoute,
  ControlIndexRoute: ControlIndexRoute,
}

const ControlRouteWithChildren =
  ControlRoute._addFileChildren(ControlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ControlRoute: ControlRouteWithChildren,
  DownloadRoute: DownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
